### ISSUE TITLE
MessageBar is not able to show above or infront of an AlertDialog's dimmed background.

### ISSUE THREAD

**Issue by Hassaan** [SimonVT/MessageBar#5]
As the title stats, when an AlertDialog is showing and `MessageBar(...)` is called, the MessageBar is always displayed behind the dimmed background of the AlertDialog. 

I think this has to be fixed because a Toast is able to be displayed above/infront of an AlertDialog.

I tried playing around with the internal `mContainer` View by calling the [View.bringToFront()](http://developer.android.com/reference/android/view/View.html#bringToFront%28%29) method, but that didn't work either.

**Comment by SimonVT** [comment]
The message bar is local to the activity. If something covers it, they aren't shown. There's nothing to do about this, and it's the point of this library.

The reason `View#bringToFront` doesn't work is that the dialog has its own window on top of the activity. They're not in the same view hierarchy.
