### ISSUE TITLE
Switching back to a Fragment sees an bottom empty MessageBar that never disappears.

### ISSUE THREAD

**Issue by danielsunyu** [SimonVT/MessageBar#7]
I embed the MessageBar in an Fragment. It works fine at first. But when I switch out and in to the same Fragment again. An empty MessageBar displays at the bottom of the screen and never disappears. I have no clue how to fix this.

Is it because in Fragment you can't construct a MessageBar instance using MessageBar mb = new MessageBar(getActivity()); ? I note in the doc it says that in Fragment you have to use a different method. But after following the doc and run the app, it crashes and reports a bug in init() of MessageBar saying that "layout_width" attribute not provided...

In the sample I noticed that there is no demo showing how to use one in Fragment. Would you please complete the demo? Thank you!

**Comment by SimonVT** [comment]
Yes, you have to use new MessageBar(View) in your fragment, and manually add the required views to your layout. If it's complaining about missing layout_width, then you're missing layout_width on one of your views. That's not an issue with this library.
