### ISSUE TITLE
Issue when using with Support Library v7

### ISSUE THREAD

**Issue by mradzinski** [SimonVT/MessageBar#9]
Calling MessageBar messageBar = new MessageBar(this); from an activity extending ActionBarActivity (Support Library v7) gives an XML Inflating error:

Binary XML file line #25: Error inflating class android.support.v7.internal.widget.ActionBarView

It seems that by "injecting" the message layout into the activity layout breaks the ActionBarView layout, thus causing the error.

I've tried the same with a regular activity and it works.
Can you give it a try and see if it works on your side?

**Comment by SimonVT** [comment]
Don't attach MessageBar until the content view has been set, otherwise it would be behind your content.

**Comment by laaptu** [comment]
For `MessageBar` to work with `Them.AppCompat`,following must be included in

```
    <item name="messageBarContainerStyle">@style/MessageBar.Container</item>
    <item name="messageBarTextStyle">@style/MessageBar.Message</item>
    <item name="messageBarButtonStyle">@style/MessageBar.Button</item>
```

in `themes.xml` of 
- values
- values-v11
- values-v14,

otherwise ,there will be force close stating to supply `layout_width` attribute.
